### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by srcrs** [viko16/vuepress-plugin-permalink-pinyin#2]

**Comment by viko16** [comment]
@srcrs 是否提供更多的信息？是怎么样的不能使用？

**Comment by srcrs** [comment]
就是安装完插件之后，重新构建，汉字标题并未改变，也是按照README方式配置的

**Comment by srcrs** [comment]
咱们这个对于文章的路径也是有要求的吗，我把文章换一个路径就好了

**Comment by viko16** [comment]
@srcrs 方便提供下之前使用的路径吗？我看看是不是兼容性问题

**Comment by srcrs** [comment]
之前文章是在这里：D:\srcrs.github.io\src\_posts
现在文章放到这里：D:\srcrs.github.io\src

**Comment by srcrs** [comment]
好多主题都是将文章放到_posts中，可以适配下这个路径

**Comment by viko16** [comment]
实验了一下，这种路径没发现有什么问题，请看以下 Demo
https://codesandbox.io/s/vuepress-plugin-permalink-pinyin-yanzheng-5kw9b?file=/src/_posts/.vuepress/config.js

如果可以的话，请提供一下最小可复现仓库
