### ISSUE TITLE
控制台仍然报警告，路由不能是中文名，

### ISSUE THREAD

**Issue by viceroyliu** [viko16/vuepress-plugin-permalink-pinyin#4]
可以解决这个警告嘛，我的意思是在路由被创建完成时，名称就会转换为pinyin

**Comment by viceroyliu** [comment]
警告内容：

[vue-router] Route with path "/categories/闲杂笔记/index.html" contains unencoded characters, make sure your path is correctly encoded before passing it to the router. Use encodeURI to encode static segments of your path.

**Comment by bourbon08** [comment]
我也报错, 我的解决方法是
node_modules\vuepress-plugin-permalink-pinyin\index.js
修改源码为: 
```
       const options = Object.assign({}, pluginConfig, { ignore: ['/', '.'] })

      $page.path = pathArr.map(str => slugify(str, options)).join('/')
      $page.regularPath = pathArr.map(str => slugify(str, options)).join('/')
```
@viko16

**Comment by viko16** [comment]
在 1.1.0 中修复了这个问题，非常感谢 @bourbon08 ！
